[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true

# incomplete list at https://www.evmdiff.com/features?name=PUSH0&kind=opcode
[profile.metis]
evm_version = 'paris'

[profile.mainnet]
evm_version = 'shanghai'

[profile.arbitrum]
evm_version = 'shanghai'

[profile.optimism]
evm_version = 'shanghai'

[profile.base]
evm_version = 'shanghai'

[profile.polygon]
evm_version = 'shanghai'

[profile.avalanche]
evm_version = 'shanghai'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
gnosis = "${RPC_GNOSIS}"
scroll = "${RPC_SCROLL}"
bnb = "${RPC_BNB}"

[etherscan]
mainnet = { key="${ETHERSCAN_API_KEY_MAINNET}", chainId=1 }
optimism = { key="${ETHERSCAN_API_KEY_OPTIMISM}", chainId=10 }
avalanche = { key="${ETHERSCAN_API_KEY_AVALANCHE}", chainId=43114 }
polygon = { key="${ETHERSCAN_API_KEY_POLYGON}", chainId=137 }
arbitrum = { key="${ETHERSCAN_API_KEY_ARBITRUM}", chainId=42161 }
fantom = { key="${ETHERSCAN_API_KEY_FANTOM}", chainId=250 }
metis = { key="any", chainId=1088, url='https://andromeda-explorer.metis.io/' }

# See more config options https://github.com/gakonst/foundry/tree/master/config
